name: "Check Branch"

on:
  pull_request:
    branches:
      - main

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        if: github.base_ref == 'main' && github.head_ref != 'develop'
        run: |
          echo "ERROR: PRs to 'main' branch must come from 'develop' branch only"
          exit 1
