name: Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

env:
  NODE_VERSION: 20
  PNPM_VERSION: 9

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'main' &&
      github.event.pull_request.head.ref == 'develop'
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: "https://registry.npmjs.org/"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Determine Release Type
        id: determine_release_type
        run: |
          LABELS=$(echo '${{ toJson(github.event.pull_request.labels) }}' | jq -r '.[].name')

          IS_BETA=false
          IS_STABLE=false

          while IFS= read -r label; do
            case "$label" in
              "release:beta")
                IS_BETA=true
                ;;
              "release:stable")
                IS_STABLE=true
                ;;
            esac
          done <<< "$LABELS"

          if [ "$IS_BETA" = false ] && [ "$IS_STABLE" = false ]; then
            echo "::error::No release label found. Add either 'release:beta' or 'release:stable' label."
            exit 1
          fi

          if [ "$IS_BETA" = true ] && [ "$IS_STABLE" = true ]; then
            echo "::error::Both stable and beta labels found. Please choose only one."
            exit 1
          fi

          if [ "$IS_BETA" = true ]; then
            echo "release_type=beta" >> "$GITHUB_OUTPUT"
            echo "npm_tag=beta" >> "$GITHUB_OUTPUT"
          else
            echo "release_type=stable" >> "$GITHUB_OUTPUT"
            echo "npm_tag=latest" >> "$GITHUB_OUTPUT"
          fi

      - name: Lint and Format
        run: pnpm run check

      - name: Run Tests
        run: pnpm run test

      - name: Enter Beta Pre-Release Mode
        if: steps.determine_release_type.outputs.release_type == 'beta'
        run: |
          pnpm changeset pre exit
          pnpm changeset pre enter beta

      - name: Exit Pre-Release Mode
        if: steps.determine_release_type.outputs.release_type == 'stable'
        run: pnpm changeset pre exit || true

      - name: Version Packages
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        run: pnpm changeset version

      - name: Build Packages
        run: pnpm build

      - name: Commit Version Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "chore: update versions and changelogs"
            git push origin main
          fi

      - name: Publish Packages
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc

          if [ "${{ steps.determine_release_type.outputs.release_type }}" = "beta" ]; then
            pnpm changeset version
            pnpm changeset publish
          else
            pnpm changeset version
            pnpm changeset publish
          fi
